### ISSUE TITLE
Issue with Microsoft.CodeAnalysis.* packages

### ISSUE THREAD

**Issue by johnkattenhorn** [OrleansContrib/Orleankka#100]
We use the current publish NuGet packages for Orleankka but we are getting some weirdness.

If we run our test suite using Visual Studio then everything is fine. If we use our VSO Build Agent Orleankka.TestKit complains about not being able to find `Microsoft.CodeAnalysis.CSharp` version 1.0.0. 

Redirects are all configured so I pulled the latest source and surprised to see that already paket.dependencies already has entries for 1.1.1. 

Our code was at 1.1.2 so I back revved it to 1.1.1 and still didn't work. So I back rev'd it to 1.0.0 and it complained about System.Collections.Immutable 1.1.36 so did this one and the tests on the build agent worked again.

The test worked all the time locally so still can't explain that. Are the nugget packages for Orleankka the same as the master branch ?

I've never used Paket before or Nake but I was wondering if I should try to submit a PR with all of the packages versions refreshed, I see most are pinned and for good reason no doubt, are they any that we already know will not work ?

**Comment by yevhen** [comment]
Let me check that. I don't have any problems  running NUnit tests both within VS and cli.

**Comment by johnkattenhorn** [comment]
Thanks @Yevhen, we thought we fixed it but it now appears to ask for both 1.0.0 and 1.1.0 so I'm just looking into again.

**Comment by AntyaDev** [comment]
wow it's getting hot)

**Comment by johnkattenhorn** [comment]
@jkonecki fixed this by making sure that all of the Orleankka dependencies were the same.

**Comment by AntyaDev** [comment]
cool!
