### ISSUE TITLE
Orleankka Support for Azure Gateway without using Cloud Services ?

### ISSUE THREAD

**Issue by johnkattenhorn** [OrleansContrib/Orleankka#101]
We've recently move away from Cloud Services to TopShelf implemented exe's to allow us to deploy more rapidly. 

If we configure to use Gateway Ports etc. everything connects up but I couldn't figure out why I couldn't just continue to use the Azure Gateway type without using AzureClientConfigurator / AzureServerConfigurator as they have a dependency on AzureSilo ?

I've had a dig through the source and I can see the AzureSilo is doing a bunch of additional work. So I thought I'd stop and ask if this is a supported configuration. 

If it is support then the outlining code configuration settings for the silo and the client would be much appreciated.

NB. I've checked out the ServiceFabric Azure @ReubenBond built as that works he set's a bunch of settings on the SiloHost manually and I don't think I can get to the underlying SiloHost inside Orleankka can I ?

I've also asked this question over at the Orleans repo to see if it is a supported situation from an Orleans perspective.

**Comment by AntyaDev** [comment]
@yevhen what do you think?

**Comment by johnkattenhorn** [comment]
@AntyaDev - It seems from an Orleans perspective is should be possible but still waiting for some more guidance, here is the issue I raised over there 👍 

https://github.com/dotnet/orleans/issues/1811

**Comment by AntyaDev** [comment]
@johnkattenhorn :+1:

**Comment by yevhen** [comment]
Hi @johnkattenhorn 

Ye, I'll update api to make it possible to work with/without cloud services. At Youscan we use custom setup hosting Orleans in YAMS, which is itself hosted in Cloud Service. I remember I still owe to write a blog post on our YAMS setup. Willl get to this soon.

**Comment by yevhen** [comment]
Fixed by https://github.com/OrleansContrib/Orleankka/commit/e296745bc9eceb75cbabef65c8d287b2136599b1 and sample configuration is added by https://github.com/OrleansContrib/Orleankka/commit/e9e770cf7ddb2f9011e9ea6ff4924697705db9f9

Next version of Orleankka won't have dedicated Azure package. We won't hide Orleans and all of the azure configuration could be done with `ClientConfiguration`
