### ISSUE TITLE
do not display default measurement values for runs to which the student did not participate

### ISSUE THREAD

**Issue by ca-ta** [OrleansContrib/Orleankka#102]
see https://aba.experiad.com/gs/d7f7bcf4fbd24786a5e02cc784c0fa62/view/agprog/909e14c1d87b4c539d80e6d3d3df5447/target/Skills%20Drill
Dipali Rizzo was not present for run 2, yet the default measurement values are displayed as awarded (the total session score is correct)

**Comment by yevhen** [comment]
Huh? I think you want to post this somewhere else :)

**Comment by ca-ta** [comment]
Ouch - sorry @yevhen 
It seems I was browsing the Orleankka repo and filed it here by mistake. Working too hard these days... :-) - I'll clean up
