### ISSUE TITLE
Silo/Actor-level interceptors

### ISSUE THREAD

**Issue by yevhen** [OrleansContrib/Orleankka#108]
Currentlly, to achieve something similar, people use inheritance, which is a wrong way to tackle the problem. Orthogonal concerns should not be added via inheritance. 

Interceptors should have access to Actor instance and its services. For example interceptor can auto deactivate actor on concurrent writes (split-brain).

This is also requried to be on par with Orleans functionality.

**Comment by aprooks** [comment]
did a quick check on interceptors and have following thoughts and questions.

I am not sure if we need actor/grain level interceptors as they still require inheritance to work. We can achieve same behavior via `OnReceive` hook.

As for global interceptor, we could expose explicit actor extention like:
```
ActorSystem.Configure()
  .Playground()
  .WithInterceptor( myInterceptor)
  ...
  .Done()
```
at the moment, Orleans itself supports only a single interceptor https://github.com/dotnet/orleans/issues/2000 but we could overcome it with a simple delegate composition.

what do you think interceptor signature would be? Message, ActorPath, GrainType?

**Comment by yevhen** [comment]
Misclicked 😂

**Comment by yevhen** [comment]
I've just pushed draft impl. Forgot to mention id of this issue. Check it out

**Comment by yevhen** [comment]
Bottom line. It took a dirty hack to implement. This is due to absence of clear client/server separation. I plan to split core into client and runtime libraries similar to how Orleans itself is organized.

**Comment by aprooks** [comment]
Just as a note, would be good to have interceptor applied to actor hierarchy. Maybe by adding attribute to parent class.

**Comment by yevhen** [comment]
@aprooks  What do you mean  by "actor hierarchy"?

**Comment by aprooks** [comment]
@yevgen: "add Interceptor to all actors inherited from "Projection" base class"

**Comment by yevhen** [comment]
@aprooks sure, this is already supported! 

Interceptor registers named Invokers - they are not scoped to a particular type. Then you can specify name of the particular invoker via attribute. Example follows:

```cs
public class Interceptor : IInterceptor
{
    public void Install(IInvocationPipeline pipeline, object properties)
    {
        pipeline.Register("projections", new ProjectionInvoker());
    }

    class ProjectionInvoker : ActorInvoker
    {
        public override async Task<object> OnReceive(Actor actor, object message)
        {
            // do smth with message, act before ...
            var result = await base.OnReceive(actor, message);
            // ... and act after
            return result;
        }
    }
}

[Invoker("projections")]
public abstract class ProjectionActor : Actor
{}
```

**Comment by yevhen** [comment]
@aprooks also, you can intercept OnReminder/OnActivate/OnDeactivate invocations.

Plus, you can chain invokers easily:

```cs
pipeline.Register("projections", new LoggingInvoker(new SecurityInvoker(new ProjectionInvoker()));
```

The last, automatically created invoker in pipeline will simply invoke respective methods on actor.

**Comment by yevhen** [comment]
@aprooks you can also register global invoker but semantics is different that in Orleans.

```
pipeline.Register(new LoggingInvoker());
```
It will called for any actor that doesn't specify invoker explicitly via `[Invoker(name)]` attribute.

**Comment by aprooks** [comment]
Seems like this one covers all the use cases we have, but I will keep looking into to be sure

**Comment by yevhen** [comment]
@aprooks ye, I've tried to cover all possible use-cases.

**Comment by yevhen** [comment]
The only limitation - it doesn't cover messages delievered via stream callback. We need to tackle that somehow as well

**Comment by yevhen** [comment]
@aprooks looks like this feature is complete now
