### ISSUE TITLE
Stateful actors

### ISSUE THREAD

**Issue by yevhen** [OrleansContrib/Orleankka#109]
This is one of the biggest omissions. Adding support for stateful actors will open up access to ready-made storage providers which were written by Olreans community. Could be useful fior newcomers.

**Comment by yevhen** [comment]
After spending some time looking at current state of orleans.peristence, both built-in and contributed providers - I've changed my mind. It's better to implement your own tailor-made persitence than use this trash.

**Comment by Neftedollar** [comment]
So is orleankka has no Orleans' persistence API?

**Comment by yevhen** [comment]
@Neftedollar you can use Orleans declarative persistence via facets. I don't have dedicated sample but you can use this [test](https://github.com/OrleansContrib/Orleankka/blob/master/Tests/Orleankka.Tests/Features/Storage_provider_facet.cs) as an example of how persistence can be used with Orleankka. In nutshell, you need to register storage provider (any orleans built-in or contrib provided) like [this](https://github.com/OrleansContrib/Orleankka/blob/master/Tests/Orleankka.Tests/Features/Storage_provider_facet.cs#L27) and then use ctor based [injection](https://github.com/OrleansContrib/Orleankka/blob/master/Tests/Orleankka.Tests/Features/Storage_provider_facet.cs#L27) via special attribute (provided by Orleankka). All the rest is the same. The state will be automatically pre-loaded on activation, etc.

The ProcessManager (C#/FSM) features a working [demo](https://github.com/OrleansContrib/Orleankka/blob/master/Samples/CSharp/FSM/ProcessManager/Program.cs#L38) of how the custom storage provider could be used with Orleankka. But any other storage provider could be used instead (anything which implements native `IGrainStorage` interface).

**Comment by Neftedollar** [comment]
@yevhen awesome. Thank you.
