### ISSUE TITLE
FSM (switchable behaviors)

### ISSUE THREAD

**Issue by yevhen** [OrleansContrib/Orleankka#111]
The idea is to have built-in FSM support in Orleankka similar to what Akka.Net have with Become but adapted for Orleans virtual actors. Phase 2 will be to introduce hierarchical FSM (HSM) like what Stateless provides at the moment.

That should make Orleankka more close to Akka in terms of application level features and should also make writing actors with complex behaviors more pleasant. I plan to port some of the work (and concepts) I did for latest release of Stateless.

P.S. That will be the last feature before v1 release. Then only documentation will be added.

**Comment by yevhen** [comment]
This feature is now concept-complete. Optimizations and various other improvements will be done in minor release after v1

**Comment by Neftedollar** [comment]
Any concept examples?
