### ISSUE TITLE
Split F# api into client and server

### ISSUE THREAD

**Issue by yevhen** [OrleansContrib/Orleankka#112]
Similar to C# version we should have FSharp.Runtime library and corresponding nuget package.

**Comment by aprooks** [comment]
I've taken a brief look on this. The task seem to be following: 

- [ ] Remove Orleankka.Runtime dependency from current FSharp.API project
- [ ] Create new project depending on Orleankka.Runtime and move everything cluster related to this one
- [ ] Change nake.bat to publish nuget

I also don't like inconsistent naming of project folder and name (FSharp.API and Orleankka.FSharp) any reasons to keep this? cc @AntyaDev

**Comment by yevhen** [comment]
Yes, yes, yes.

Projects/folders should be named Orleankka.FSharp and Orleankka.FSharp.Runtime.

**Comment by yevhen** [comment]
@aprooks Big Thanks!
