### ISSUE TITLE
Complete F# configuration api

### ISSUE THREAD

**Issue by yevhen** [OrleansContrib/Orleankka#113]
I understand that fluent DSL used by C# version might not be usable in F# and so @AntyaDev created an alternative function-based api for F#. Unfortunately it's not feature complete with C# version: registration of stream providers / interceptors and some of the other things is missing.

Would be great if we can make it fully cover C# version (only with more convenient api).

**Comment by aprooks** [comment]
what else do we have missing?

**Comment by yevhen** [comment]
I think we need to have F# counterparts of Bootstrapper and Interceptor similar to what we have with F# Actor. So ppl don't need to bother with task -> task<unit> conversions and so on.

**Comment by yevhen** [comment]
But we already have an issue for that https://github.com/OrleansContrib/Orleankka/issues/122

**Comment by yevhen** [comment]
I'll check resulting api once I have more time (tomorrow)

**Comment by yevhen** [comment]
@aprooks Can I close this one? Looks like rest is already covered by #122

**Comment by aprooks** [comment]
yes could not find other use cases not mentioned in #122
