### ISSUE TITLE
Resuming client stream subscription

### ISSUE THREAD

**Issue by mhertis** [OrleansContrib/Orleankka#114]
There is no option in Orleankka to Resume client stream subscription. Our client is unstable and is subscribing over and over again until it blows up pubsub store.  [More info](https://github.com/dotnet/orleans/issues/2505).

**Comment by yevhen** [comment]
Which version you are on now?

**Comment by mhertis** [comment]
0.23.0

**Comment by yevhen** [comment]
ye, that's old. Do you use declarative stream subscriptions?

**Comment by mhertis** [comment]
No, in this case, we are using explicit subscriptions.

**Comment by yevhen** [comment]
If you're not using declarative stream subscriptions - you can try latest version (I'll push update today) there  this was fixed.

**Comment by mhertis** [comment]
We are using declarative stream subscriptions on some other parts of the application. I can't update while we don't figure out migration path for declarative subscriptions.

But I can make some reflection magic, to mimic fixes of latest version.

**Comment by yevhen** [comment]
yep, should not be hard ))

**Comment by yevhen** [comment]
https://github.com/OrleansContrib/Orleankka/blob/v1/Source/Orleankka/StreamSubscription.cs#L13 get this one by reflection

**Comment by mhertis** [comment]
It almost works. =D
```
 static class StreamSubscriptionExtensions
    {
        private static readonly FieldInfo handle = typeof(StreamSubscription).GetTypeInfo().GetDeclaredField("handle");
        private static readonly MethodInfo GetAllSubscriptionHandles = typeof(StreamRef).GetTypeInfo().GetDeclaredMethod("GetAllSubscriptionHandles");

        /// <summary>
        ///   Returns a list of all current stream subscriptions.
        /// </summary>
        /// <returns> A promise for a list of StreamSubscription </returns>
        public static async Task<List<StreamSubscription>> Subscriptions(this StreamRef streamRef)
        {
            var handles = await (Task<IList<StreamSubscriptionHandle<object>>>)GetAllSubscriptionHandles.Invoke(streamRef, null);

            return handles.Select(CreateStreamSubscription).ToList();
        }

        private static StreamSubscription CreateStreamSubscription(StreamSubscriptionHandle<object> x)
        {
            return Activator.CreateInstance(typeof(StreamSubscription), BindingFlags.Instance | BindingFlags.NonPublic, null, new object[] { x }, null, null) as StreamSubscription;
        }

        public static Task Resume(this StreamSubscription streamSubscription, Func<object, Task> callback)
        {
            Requires.NotNull(callback, nameof(callback));
            var observer = new Observer((item, token) => callback(item));
            var subscriptionHandle = (StreamSubscriptionHandle<object>)handle.GetValue(streamSubscription);

            return subscriptionHandle.ResumeAsync(observer);
        }

        public static Task Resume<T>(this StreamSubscription streamSubscription, Func<T, Task> callback)
        {
            Requires.NotNull(callback, nameof(callback));
            return streamSubscription.Resume(item => callback((T)item));
        }

        class Observer : IAsyncObserver<object>
        {
            readonly Func<object, StreamSequenceToken, Task> callback;

            public Observer(Func<object, StreamSequenceToken, Task> callback)
            {
                this.callback = callback;
            }

            public Task OnNextAsync(object item, StreamSequenceToken token = null)
                => callback(item, token);

            public Task OnCompletedAsync() => Task.CompletedTask;
            public Task OnErrorAsync(Exception ex) => Task.CompletedTask;
        }
    }
```

After calling `StreamSubscription.Resume`, `StreamSubscriptionHandle.observer` remains `null`. I will just unsubscribe all subscriptions and resubscribe, for now. =D

**Comment by yevhen** [comment]
I've never understood why Orleans guys had not implemented subscriptions in idempotent way. Duplicate subscriptions from the same client/actor in 100% of cases is a mistake.

P.S. "StreamSubscriptionHandle.observer remains null" might be a normal behavior. Check Orleans code ..

**Comment by mhertis** [comment]
I totally agree with you and now I have discovered one more surprise...

`subscriptionHandle.ResumeAsync(observer)` returns `Task<StreamSubscriptionHandle<object>>`  - > new valid handle while old handle becomes invalid.

I think that latest Orleankka codebase does not take this behavior into account.

**Comment by yevhen** [comment]
Nice catch!
