### ISSUE TITLE
F# helpers for Bootstrappers and Interceptors

### ISSUE THREAD

**Issue by aprooks** [OrleansContrib/Orleankka#122]
I don't see a reason why Bootstrappers and Interceptors should be statefull and inherit C# object. We could have  a simple function `props ->Task<unit>` or `props -> IActorSystem -> Task<unit>`  registered as bootstrapper, and then wrapped internally as c# type. Not 100% sure it is possible though :)

something like:

``` FSharp
assemblies
|> createCluster
|> bootstrapper (fun _ -> log "bootstrapped!")
|> complete
|> start
```

**Comment by yevhen** [comment]
It's all due to Embedded system. Bootstrappers/interceptors are instantiated in different AppDomain. In C# lambdas are not serializable

**Comment by yevhen** [comment]
@aprooks any suggestions on this?

**Comment by aprooks** [comment]
not yet. Need to play a bit more with F# api
