### ISSUE TITLE
Chat Sample not working

### ISSUE THREAD

**Issue by lcpinto** [OrleansContrib/Orleankka#124]
Hi,

Chat sample is not working. Always throws the same exception:

Unable to map type 'Example.IChatRoom' to the corresponding actor type. Make sure that you've registered the assembly containing this type

**Comment by yevhen** [comment]
V1 branch?

**Comment by yevhen** [comment]
C# or F#? Observer-based or streams?

**Comment by lcpinto** [comment]
Observer-based master

**Comment by lcpinto** [comment]
Same happenning on v1 branch

**Comment by lcpinto** [comment]
streams are ok.

**Comment by lcpinto** [comment]
C#

**Comment by yevhen** [comment]
v1 demo is working fine. However, the one in the master was indeed broken. Thanks for reporting!
