### ISSUE TITLE
Support for non-public Reentrant callback

### ISSUE THREAD

**Issue by jkonecki** [OrleansContrib/Orleankka#126]
Currently static callback method that can be provided in `Reentrant` attribute has to be public. Please change the binding definition so non-public methods can be provided.
`StreamSubscription` attribute supports non-public callbacks.

**Comment by yevhen** [comment]
That's easy.

**Comment by yevhen** [comment]
I just not sure why is that a problem for you to have it public ))

**Comment by jkonecki** [comment]
1. This method is an implementation detail of the actor and is not meant to be called from outside.

2. Consistency with callback for StreamSubscription.

**Comment by yevhen** [comment]
Ok, then. Just was curious :)
