### ISSUE TITLE
Reentrant callback not invoked for Queries

### ISSUE THREAD

**Issue by jkonecki** [OrleansContrib/Orleankka#127]
I have provided a callback method using `Reentrant` attribute.
This method gets called only for messages that arrived through streams.
Queries sent directly to the actor do not invoke the callback method to check if they should be reentrant.

The expected behaviour is for all messages to invoke the callback.

**Comment by yevhen** [comment]
Hmm, let me check whether I have test for this scenario

**Comment by yevhen** [comment]
I can't reproduce it. This [test](https://github.com/OrleansContrib/Orleankka/blob/v1/Source/Orleankka.Tests/Features/Reentrant_messages.cs#L137) works as expected and [this](https://github.com/OrleansContrib/Orleankka/blob/v1/Source/Orleankka.Tests/Features/Reentrant_messages.cs#L93) line is hit when I run it under debugger, every time when message is about to be delivered .

**Comment by jkonecki** [comment]
In my case the query is sent by other actor. I wonder if it makes a
difference.

**Comment by yevhen** [comment]
That shouldn't. Callback is invoked by Orleans' dispatcher and everything goes via it (including grain extension message delivery, like streaming). The only thing you can't control with it - is reminders, due to how they delivered internally.

**Comment by yevhen** [comment]
This works as expected https://github.com/OrleansContrib/Orleankka/commit/c33f1acf0f548f8a31abd3f9e162d34d5db5b8c0

**Comment by yevhen** [comment]
Can I close this one? Have you found the problem?

**Comment by jkonecki** [comment]
I'll try to create a failing test.

**Comment by jkonecki** [comment]
Closing the issue as the problem was in my code - the type of the message wasn't matching the type provided in `Reentrant` attribute. Silly me ;-)
