### ISSUE TITLE
Resumed/Subscribed not used in StreamRefMock

### ISSUE THREAD

**Issue by mhertis** [OrleansContrib/Orleankka#129]
https://github.com/OrleansContrib/Orleankka/blob/master/Source/Orleankka.TestKit/StreamRefMock.cs#L24

**Comment by yevhen** [comment]
Good catch! What version you are on?

**Comment by mhertis** [comment]
Migrating to 1.0.1, waiting for 1.5.0 :)

**Comment by yevhen** [comment]
PR would be welcomed ))

**Comment by mhertis** [comment]
I think the best option is to delete Resumed/Subscribed/Filter properties because we do not have reference to the actor that subscribed/resumed.

Will prepare PR if we agree on this. :)

**Comment by yevhen** [comment]
@mhertis agree!
