### ISSUE TITLE
EmbeddedConfigurator registers actor types for client configuration

### ISSUE THREAD

**Issue by mhertis** [OrleansContrib/Orleankka#130]
https://github.com/OrleansContrib/Orleankka/blob/3445eefdb97e27252699649456a98c65682c3e5a/Source/Orleankka.Runtime/Embedded/EmbeddedConfigurator.cs#L91

should be 
`            foreach (var type in assemblies.SelectMany(x => x.ActorInterfaces()))`

or replaced with
`client.Assemblies(assemblies);`

**Comment by yevhen** [comment]
Could you make a PR?

**Comment by yevhen** [comment]
How does it affect you (in a bad way)?

**Comment by mhertis** [comment]
We are migrating to 1.0.1 and our actors don't have interfaces. When using EmbeddedConfigurator actors were registered but were not not with ClientConfigurator.

Although, it will be usable (simplify migration) if registration of actor types will still be supported on ClientConfigurator.

**Comment by mhertis** [comment]
Should I make EmbeddedConfigurator to behave as ClientConfigurator? Also some examples will need fixing because of missing interfaces...

**Comment by yevhen** [comment]
Yes, in 1.5 EmbeddedConfigurator is indeed a ClientConfigurator

**Comment by mhertis** [comment]
Oh, I see, was looking at master branch :)
