### ISSUE TITLE
Thread model?

### ISSUE THREAD

**Issue by ShalokShalom** [OrleansContrib/Orleankka#140]
Apache Storm uses OS isolation and Akka pure cooperative objects on OS threads. 

How does Orleankka do this?

**Comment by aprooks** [comment]
Orleankka is an interface wrapper over Orleans. Here is some info and further reading ling on how Orleans handling multi-threading http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/External-Tasks-and-Grains.html?q=tasks

**Comment by ShalokShalom** [comment]
Thanks
