### ISSUE TITLE
Can Orleankka integrate with this architecture?

### ISSUE THREAD

**Issue by JbmOnGitHub** [OrleansContrib/Orleankka#141]
First of all, thank you for this great project!! I learned a lot of things.

I try to integrate cqrs & eventsourcing into my architecture and I try to find out if orleankka could match.

The need would be that Orleankka is the "message transmitter" (as shown below) that depends on my domain but not the other way around.

Q1 : The videos pointed in the readme of the project make me think that it is possible with Orleans so it should be the same with Orleankaa?

Q2 : I have look at the issue "help wanted" for an [example of Http-endpoint with WebApi (C#)](https://github.com/OrleansContrib/Orleankka/issues/52). Do you agree that this WebApi should expose "public commands" and perform different tasks before translating them into "domain commands"? (as shown below)

![](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQWxpY2Ugc2VuZCBhIGNvbW1hbmQgdG8gdGhlIHN5c3RlbQoAHgUtPnB1YmxpYyBBUEk6IFMAKgYADAcAMAcKbm90ZSByaWdodCBvZgAVCAArBUF1ZGl0LCBhdXRob3JpemUsXG5zaG9ydCB2YWxpZGF0ZS4uLi5cbmFuZCBidWlsZFxuYSBkb21haW4AVAkAdQotPk1lc3NhZ2UgdHJhbnNtaXR0ZXIAgQsJACgPAIEGDgAkFXNlYXJjaCBhAIEHBlxuAHIHcmVjZXB0ZXIKAFsTLT5EAIEYBmFnZ3JlZ2F0ZTogVACBBgcAgjYFAIF9FgAjEmRlY2lkZSB0byBjaGFuZ2VcbgCCdAV0YXRlIG9mAIJ6DAAqIGFwcGx5AIMyBWRlY2lzaW9ucwoAgRUQAIIjFwCCPwgAfQcgZXZlbnRzAIJlDQCEIgYAg3AJQUNLL05BQ0sK&s=napkin?raw=true)

**Comment by aprooks** [comment]
In short, yes it can. 

Though I don't see why this message transmitter is stateful and why it should benefit from Orleans'es architecture

**Comment by aprooks** [comment]
Q1. Orleankka is an interface facade on top of Orleans, so anything you can do with Orleans should be possible with Orleankka and vice versa. Each interfaces having their own pros/cons

**Comment by aprooks** [comment]
Q2. I would not call "adit, authorisation and validations" as a command modification action. You can always add it transparently. E.g. when you send a serialized domain command  from UI you can add metadata as headers. Check this meta without modifying command itself and the relay to domain level without "modification". Also, validation rules can be either published as a contract and shared with API or even UI via Swagger notion or something else. 

Some people prefer to expose REST like api and then transform these calls to domain commands. For example, something like `PUT /user/10/password` would be translated to `UpdatePassword` command.

**Comment by JbmOnGitHub** [comment]
> Though I don't see why this message transmitter is stateful and why it should benefit from Orleans'es architecture
@aprooks : you're right. "Message transmitter" does not correctly transcribe my need of Orleans here. Maybe i have to change "Message transmitter" with "middle tiers for distributed high-scale apps" ?

**Comment by yevhen** [comment]
@JbmOnGitHub +1 to @aprooks Orleankka can be used in this architecture easily. If you want domain independence you can just use Orleankka actor as a host for the domain Aggregate and then simply transmit your command to it. Such design will give a performance boost to your app by saving on unnecessary reads (actors will be keeping you aggregates in memory and will make all operations on them thread-safe).

**Comment by yevhen** [comment]
Just don't inherit your messages from `ActorMessage` to be free from infrastructure (Orleankka) dependency. Also, you may still be dependent on `ActorMessage` and other Orleankka concepts but have your domain to be free of it by unpacking message data into an object call, like this:

```cs
class InventoryItemActor : DispatchActorGrain, IInventoryItemActor
{
      InventoryItem item;  // this is a domain aggregate you will load upon Activate

      // unpack message on wire at the boundary, all domain logic is kept inside aggregate
      IEnumerable<Event> Handle(CheckIn cmd) => item.CheckIn(cmd.Quantity);     
}
```

**Comment by aprooks** [comment]
So this way Orleans becomes also a cluster hosting solution.

**Comment by JbmOnGitHub** [comment]
@yevhen, @aprooks : Thank you for your advice, it perfectly matches what I was looking for!

**Comment by JbmOnGitHub** [comment]
My sequence diagram updated where : 

- Orleankka is the cluster hosting solution
- Domain commands as public across whole app (as mentioned by @aprooks)

![](https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgQWxpY2Ugc2VuZCBhIGNvbW1hbmQgdG8gbXkgZGlzdHJpYnV0ZWQgc3lzdGVtCgApBS0-cHVibGljIEFQSTogUwAuDQpub3RlIHJpZ2h0IG9mIAAdDGF1dGhvcml6ZSxcbmNoZWNrIG1ldGFkYXRhcwoARwotPkNsdXN0ZXIgaG9zdGluZwBbB3RoZQCBFwhcbnRvIGFuIGFjdG9yCgAgDy0-RG9tYWluIGFnZ3JlZ2F0ZQAmGwAbCACBJw8AMBJkZWNpZGUgdG8gY2hhbmdlXG50aGUgc3RhdGUgb2YAgRgFAIIbBwAqIGFwcGx5AIFJBWRlY2lzaW9ucwoAgSIQAIFxE3NlbmRcbgB3BiBldmVudACCJw4Ag0IGAIMFCUFDSy9OQUNL&s=napkin)

**Comment by aprooks** [comment]
Looks good let's. You don't need ack/nack as calls are blocking by default.
