### ISSUE TITLE
Idiomatic Sample not working - stream projection

### ISSUE THREAD

**Issue by mhertis** [OrleansContrib/Orleankka#145]
In the latest version, declarative stream subscriptions are gone. Idiomatic sample 
now uses `RegexImplicitStreamSubscription`. 

`RegexImplicitStreamSubscription` functionality differs from Orleankka declarative subscriptions, therefore Inventory class does not get any events. Did I miss something?

```    
[RegexImplicitStreamSubscription("/InventoryItem-.*/")]
public class Inventory : DispatchActorGrain, IInventory {}

**Comment by alexeyzimarev** [comment]
Ok, there are really a few issues. 

- Subscriptions work in a way that for each new stream that matches the implicit subscription filter, Orleans creates a new grain. Subscribing to multiple streams from one grain is impossible.
- The Regex match for some reason doesn't work although the expression is correct. I solved it by creating another attribute that works with `StartsWith`.
- The subscription must be done explicitly when the actor is activated. Events aren't being sent to the actor as other messages.

My changes are:

```csharp
    [StartsWithImplicitStreamSubscription("InventoryItem")]
    public class Inventory : DispatchActorGrain, IInventory, IGrainWithGuidCompoundKey
    {
        async Task On(Activate _)
        {
            var streamProvider = GetStreamProvider("sms");

            var guid = this.GetPrimaryKey(out var extension);
            var stream = streamProvider.GetStream<EventEnvelope>(guid, extension);

            await stream.SubscribeAsync((envelope, token) => Receive(envelope.Event));
        }
        
        void On(InventoryItemCreated e)     => items[Id] = new InventoryItemDetails(e.Name, 0, true);
        void On(InventoryItemCheckedIn e)   => items[Id].Total += e.Quantity;
        void On(InventoryItemCheckedOut e)  => items[Id].Total -= e.Quantity;
        void On(InventoryItemDeactivated e) => items[Id].Active = false;
        void On(InventoryItemRenamed e)     => items[Id].Name   = e.NewName;
        
        static readonly Dictionary<string, InventoryItemDetails> items =
            new Dictionary<string, InventoryItemDetails>();

        InventoryItemDetails[] Answer(GetInventoryItems _) => items.Values.ToArray();
        int Answer(GetInventoryItemsTotal _) => items.Values.Sum(x => x.Total);
    }

    public class StartsWithPredicate : IStreamNamespacePredicate
    {
        readonly string startsWith;

        public StartsWithPredicate(string startsWith) => this.startsWith = startsWith;

        public bool IsMatch(string streamNamespace) => streamNamespace.StartsWith(startsWith);
    }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    public class StartsWithImplicitStreamSubscriptionAttribute : ImplicitStreamSubscriptionAttribute
    {
        public StartsWithImplicitStreamSubscriptionAttribute(string startsWith)
            : base(new StartsWithPredicate(startsWith))
        { }
    }
```

**Comment by alexeyzimarev** [comment]
I agree that it should be one actor per projection, not per aggregate actor, but the idea of pushing to an aggregate-type stream doesn't sound appealing to me, since ideally, developers should be able to choose between the aggregate-type stream to make aggregate state snapshots, which is a marginal use-case, since the aggregate actor already keeps its state, and the `all`-stream, which I see as a default stream for projections.
