### ISSUE TITLE
Document F# bugger or add a startup check

### ISSUE THREAD

**Issue by aprooks** [OrleansContrib/Orleankka#148]
https://github.com/orleanscontrib/orleankka/blob/master/Samples/FSharp/Streams/Chat.Shared/Bugger.fs 

this one should either be documented or a startup check added that an appPart assembly contains a reference to something from Orleans. Otherwise, first use experience is troublesome. 

see #147

**Comment by yevhen** [comment]
Don't fight the framework;)
