### ISSUE TITLE
Create template for dotnet cli tool

### ISSUE THREAD

**Issue by Neftedollar** [OrleansContrib/Orleankka#149]
I think it would be comfortable to have it.
Example usage:
`dotnet new orleannka -lang F# -server `

**Comment by yevhen** [comment]
Cool. I would gladly accept a PR 👍

**Comment by Neftedollar** [comment]
I'm using this scaffold now. 
I don't use C# version, so if I'm going to create the template, it'll be F# only
https://github.com/Neftedollar/fsharp-orleankka-scaffold

**Comment by yevhen** [comment]
Awesome! 💪 Can’t wait!

**Comment by Neftedollar** [comment]
https://github.com/OrleansContrib/Orleankka/pull/155
PR
