### ISSUE TITLE
Storage provider issue

### ISSUE THREAD

**Issue by jpiquot** [OrleansContrib/Orleankka#153]
Hi,

It seems that using the orleans persistence providers does not work as expected. It stores the wrong name for the grain. The grain full name is replaced by the provider name.

```
CTOR of actor 1 :
     public TransactionStatisticPeriodGrain
            ([UseStorageProvider(nameof(BusinessIntelligence))] IStorage<TransactionStatisticPeriodState> storage)
            : base(storage) { }

CTOR of actor 2 :
     public TransactionStatisticGrain
            ([UseStorageProvider(nameof(BusinessIntelligence))] IStorage<TransactionStatisticState> storage)
            : base(storage) { }


```

![image](https://user-images.githubusercontent.com/6775094/57505353-52e97c00-72f8-11e9-8156-5cd1788a38cf.png)

**Comment by yevhen** [comment]
This was fixed in 2.3.4
