### ISSUE TITLE
What should I do to call orleankka actor from orleans silo?

### ISSUE THREAD

**Issue by Neftedollar** [OrleansContrib/Orleankka#157]
Hey!
How can I call orleankka's actors from Orleans?
How can I do it vice versa? 

Thank you!

**Comment by Neftedollar** [comment]
As I understand orleankka's actors should call `Initialize` method before call `OnActivationAsync`, but when I try to get grain via `IGrainFactory` it's not called and then `OnActivationAsync` fails with `Null reference exception` cause it's trying to access middleware which not initialized.

**Comment by Neftedollar** [comment]
The simplest way is to call `UseOrleanka` and then inject `IActorSystem` as a dependency.
But maybe I can do something without `IActorSystem`?

**Comment by yevhen** [comment]
Yes, inject `IActorSystem` into Orleans `Grain` and then you can send messages to Orleankka's actors

**Comment by yevhen** [comment]
@Neftedollar need any further help with this?

**Comment by Neftedollar** [comment]
@yevhen no, thnx
