### ISSUE TITLE
Auto.Interfaces assembly generated in wrong folder

### ISSUE THREAD

**Issue by jkonecki** [OrleansContrib/Orleankka#165]
This issue was found in _Transitional 004_ build.

`ActorInterfaceDeclaration` generates `Orleankka.Auto.Interfaces` assembly in the wrong folder when running in a web application project (eg. ASP.NET Web API).

The issue is in line 30:

https://github.com/OrleansContrib/Orleankka/blob/b084427a85b94c63dfa5ed5bdebf4d6ecd2b0edc/Source/Orleankka/Core/ActorInterfaceDeclaration.cs#L30

`AppDomain.CurrentDomain.BaseDirectory` returns the root folder for web applications instead of `/bin` subfolder.

The fix would involve changing

`AppDomain.CurrentDomain.BaseDirectory` 

to

`AppDomain.CurrentDomain.RelativeSearchPath ?? AppDomain.CurrentDomain.BaseDirectory` 

Without the fix Orleankka clients hosted in ASP.NET web projects fail to start with `FileNotFoundException` when trying to load `Orleankka.Auto.Interfaces` from `/bin` folder.

**Comment by yevhen** [comment]
Oh, gosh. That's bad. It means that all versions > 004 are not usable in this scenario too :(

We don't use web application projects at my company (we host asp.net in console app) so I didn't have a chance to catch it. Sorry (

I'll create an alternative string of releases with the patch, starting from 004  and up until 21. Something like `transitional-wapfix-0XX`. But that will take some time((

**Comment by jkonecki** [comment]
Don't worry about it - unless there are others affected.

I plan to migrate Web projects from .NET Framework to Core anyway.

**Comment by yevhen** [comment]
Well, there could be other ppl affected. 

Added information on an alternative string of releases. to migration [guide](https://github.com/OrleansContrib/Orleankka/wiki/Migration-from-1.5-to-2.0#version-for-aspnet-web-projects). Let me know if it works for you so I can close the issue.

**Comment by jkonecki** [comment]
I confirm the assembly is generated in the correct folder.
