### ISSUE TITLE
Feature request: StreamRefMiddleware

### ISSUE THREAD

**Issue by Jubast** [OrleansContrib/Orleankka#173]
Hi! 

Would it be possible to add a StreamRefMiddleware (similar to ActorRefMiddleware)?

When streaming messages I would like to enrich messages with some metadata from orleans `RequestContext`. Currently this is solved by overriding `IActorSystem.StreamOf` and implementing a custom `StreamOf`

sample code:
```cs
public class EnrichedActorSystem : IActorSystem
{
    public EnrichedActorSystem(IActorSystem system)
    {
        this.system = system;
    }

    public ActorRef ActorOf(ActorPath path) => new EnrichedActorRef(system.ActorOf(path));
    public StreamRef<T> StreamOf<T>(StreamPath path) => new EnrichedStreamRef<T>(system.StreamOf<T>(path));
    public ClientRef ClientOf(string path) => system.ClientOf(path);
}

public class MyService
{
    private readonly IActorSystem _system;
    public MyService(IActorSystem system)
    {
        _system = new EnrichedActorSystem(system);
    }
}
```

or in actor:

```cs
public class MyActorGrain : ActorGrain, IMyActorGrain
{
    public new IActorSystem System => new EnrichedActorSystem(base.System);
}
```

If StreamRefMiddleware was available I would be able to replace the `EnrichedActorSystem` with `ActorRefMiddleware` and `StreamRefMiddleware`

I was thinking of something like:
```cs
public interface IStreamRefMiddleware
{
    Task Publish<TMessage>(StreamPath path, TMessage message, Func<TMessage, Task> next) where TMessage: PublishMessage;
    Task Receive<TMessage>(StreamPath path, TMessage message, Func<TMessage, Task> next) where TMessage: StreamMessage;
}
```

I am prepared to create a PR if you agree with this feature request

**Comment by yevhen** [comment]
Ye, I was considering this feature. Just didn’t have time and real production necessity to implement it. I’ll be happy to take PR!

**Comment by yevhen** [comment]
@Jubast pushed [3.5](https://github.com/OrleansContrib/Orleankka/releases/tag/3.5) release. Thanks for contribution!

**Comment by Jubast** [comment]
Thank you 👍
