### ISSUE TITLE
Missing NuGet for Orleankka.TestKit version 7.0.0

### ISSUE THREAD

**Issue by Mojster** [OrleansContrib/Orleankka#180]
Latest version of NuGet for Orleankka.Test.Kit is still at 3.6.3.

Could you publish the 7.0.0. version, so we could use it with the latest Orleankka.

**Comment by yevhen** [comment]
Ouch, sorry! Didn't notice it. Will do today!

**Comment by yevhen** [comment]
Done https://www.nuget.org/packages/Orleankka.TestKit/7.0.0
