### ISSUE TITLE
Support for Microsoft Service Fabric Reliable Service

### ISSUE THREAD

**Issue by varghesep** [OrleansContrib/Orleankka#37]
It is nice to have Orleankka running in Microsoft Service Fabric http://azure.microsoft.com/en-us/campaigns/service-fabric/ as a Reliable Service.

The simplicity of creating a **Service Fabric Stateless Service** via Visual Studio 2015 http://azure.microsoft.com/en-us/documentation/articles/service-fabric-reliable-services-quick-start/ and integrating Orleankka would be nice feature.

**Comment by johnkattenhorn** [comment]
As of today we are working on our first sprint with Orleankka and plan to host using Reliable Service.

We're hoping to have a working prototype within a week and we plan to commit this back to the project.

**Comment by yevhen** [comment]
That's great! @ReubenBond shared a piece of code (gist) that allows exactly that. Running Orleans (and so is Orleankka) actors on top of Service Fabric reliable services

**Comment by johnkattenhorn** [comment]
He certainly did; That's what we are starting with :-)

**Comment by yevhen** [comment]
It would be cool if you can then share what you did to make that work.

**Comment by Neftedollar** [comment]
Hi all.
Will it work with orleankka? https://github.com/OrleansContrib/OrleansFabricSilo

**Comment by yevhen** [comment]
@Neftedollar unfortunately, no. We'll try to fix this very soon.

**Comment by yevhen** [comment]
Native SF support is coming with Orleans v.1.4. Orleankka will get it automatically once released upstream.

**Comment by ReubenBond** [comment]
Yep, and if you have any specific requirements, please send them my way or open an issue against Orleans so I can accommodate them.

Orleans 1.4 will include support for hosting on SF and using SF for clustering (no external membership table required) with membership notifications coming directly from SF.

**Comment by yevhen** [comment]
@ReubenBond no, I don't have anything special. Thanks for all for the hard work!
