### ISSUE TITLE
[EXAMPLE] One-off (run-once) reminders and timers (C#)

### ISSUE THREAD

**Issue by yevhen** [OrleansContrib/Orleankka#51]
Good candidate to be merged back to the core (after some trial)

**Comment by Neftedollar** [comment]
Hey!
How can I use reminders?
Should I inject IReminderService into ActorGrain via constructor? Or should I do something else?

**Comment by Neftedollar** [comment]
Oh! I see!
I just should call `this.Reminders` as I understand, and use it

**Comment by yevhen** [comment]
Yes

**Comment by yevhen** [comment]
Timers
Reminders
Jobs
Activation

All of those are the services accessible inside actor subclass without DI

**Comment by Neftedollar** [comment]
@yevhen
Thank you very much!
Will you compile your answers into wiki or something else?
Do you need help with it?

**Comment by yevhen** [comment]
Definitely. Actor services are something which needs additional samples and documentation.

Nobody reads [api](http://orleanscontrib.github.io/Orleankka/api/Orleankka.ActorGrain.html#properties) [docs](http://orleanscontrib.github.io/Orleankka/api/Orleankka.Services.IReminderService.html) these days 😄

**Comment by Neftedollar** [comment]
@yevhen  oooh! Thank you very match!
