### ISSUE TITLE
Reactive Extensions (RX) samples

### ISSUE THREAD

**Issue by mbernard** [OrleansContrib/Orleankka#62]
On the home page of this repo you said "Reactive Extensions (RX) support (client-side observers only)". However I'm not sure how it should be used. Do you have any code samples using it?

**Comment by yevhen** [comment]
Mmm, I don't have separate example for this but `ClientObserver` implements standard `IObservable<object>` interface and that's all what is needed for RX. You can use any RX functionality (just import RX packages) including stream operators.

**Comment by mbernard** [comment]
I guess I'm missing something, because I don't see any class called `ClientObserver` in Orleans, Orleankka or Rx

**Comment by yevhen** [comment]
My bad. It's just `Observer`. It's a class in Orleankka.

**Comment by yevhen** [comment]
I have test that shows how it is used https://github.com/yevhen/Orleankka/blob/master/Source/Orleankka.Tests/Features/Observing_notifications.cs

**Comment by yevhen** [comment]
Also, I suggest you to have a look at Example.Observers.Chat demo for a more comprehensive sample. It also shows how to use ObserverCollection to implement simple pub-sub.

**Comment by mbernard** [comment]
Thanks,

However, I'm looking for something that leverage the Orleans Streams.
I guess I'll code my own thing and push a PR if you want it in Orleankka

Also, about your `Observer` class, shouldn't be called `Observable` as it inherits from IObservable and in fact is one. This is very confusing :D

**Comment by yevhen** [comment]
> However, I'm looking for something that leverage the Orleans Streams.

Unfortunately streams API is not compatible with RX at the moment. Everyone is waiting for async RX to be released by Microsoft.

> I guess I'll code my own thing and push a PR if you want it in Orleankka

That would be cool. I'll gladly accept PR.

> Also, about your Observer class, shouldn't be called Observable as it inherits from IObservable and in fact is one. This is very confusing :D

Well, could be. I'll think about better name. Thanks for suggestion.
