### ISSUE TITLE
TaskBuilder TryFinally bug

### ISSUE THREAD

**Issue by polytypic** [OrleansContrib/Orleankka#95]
Just a quick FYI, I glanced at the `TaskBuilder` code briefly, and the current [TryFinally](https://github.com/OrleansContrib/Orleankka/blob/1bc6aefd57a91fbefc3d5e13f3959a2ee4e3f3a8/Source/FSharp.Api/Task.fs#L122-L124) implementation

```fs
   member this.TryFinally(m, compensation) =
      try this.ReturnFrom m
      finally compensation()
```

probably does not work as one might expect.

**Comment by AntyaDev** [comment]
Hi @polytypic and thanks for the attention, will take a look today.

**Comment by AntyaDev** [comment]
Hi @polytypic 
I hope this is fixed the bug

https://github.com/OrleansContrib/Orleankka/pull/98

**Comment by polytypic** [comment]
Also test that the compensation is executed only after the body task has been completed rather than immediately after the body task has been constructed.

**Comment by AntyaDev** [comment]
Hi @polytypic 
added unit tests and fixed implementation.
https://github.com/OrleansContrib/Orleankka/pull/98/commits/af30bc36a5078f997de4d1aa2447b78e100d7b26

I am not sure about stack trace during exception handling.

**Comment by polytypic** [comment]
Looks more correct. 👍

I would recommend removing the [`TryFinally`](https://github.com/AntyaDev/Orleankka/blob/af30bc36a5078f997de4d1aa2447b78e100d7b26/Source/FSharp.Api/Task.fs#L132-L134) version that doesn't work correctly.

Also it would seem that the [Using](https://github.com/AntyaDev/Orleankka/blob/af30bc36a5078f997de4d1aa2447b78e100d7b26/Source/FSharp.Api/Task.fs#L136-L137) method here is not correct.  If the expression `body res` throws, then `dispose` will not be called.

Also, [these two](https://github.com/AntyaDev/Orleankka/blob/af30bc36a5078f997de4d1aa2447b78e100d7b26/Source/FSharp.Api/Task.fs#L176-L181) have the same issues.

Note that these are just issues I spotted by quickly glancing at the code.  I have not done a detailed study of the code.

**Comment by AntyaDev** [comment]
Hi @polytypic I also think that they are not correct but especially with continuation flow. Regarding Using, the Dispose will be invoked for sure because **finally** will be invoked but with wrong execution flow. 
Thank you so much for good findings:) Will fix it today.

**Comment by yevhen** [comment]
@AntyaDev can we close this one?

**Comment by AntyaDev** [comment]
@yevhen let me check it tomorrow.
